import type { ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useResumarkTheme } from './resumark-theme';

export function AuditLabel({ children, tone = 'red' }: { children: ReactNode; tone?: 'red' | 'muted' | 'light' }) { const { colors } = useResumarkTheme(); return <Text style={[styles.label, { color: tone === 'red' ? colors.red : tone === 'muted' ? colors.muted : colors.consoleText }]}>{children}</Text>; }
export function PrimaryButton({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { const { colors } = useResumarkTheme(); return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.primary, { backgroundColor: colors.score }, disabled && styles.disabled, pressed && styles.pressed]}><Text style={[styles.primaryText, { color: colors.scoreText }]}>{label}</Text><Text style={[styles.arrow, { color: colors.scoreText }]}>→</Text></Pressable>; }
export function OutlineButton({ label, onPress }: { label: string; onPress: () => void }) { const { colors } = useResumarkTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.outline, { borderColor: colors.border, backgroundColor: colors.panel }, pressed && styles.pressed]}><Text style={[styles.outlineText, { color: colors.body }]}>{label}</Text></Pressable>; }
export function PaperCard({ children, style }: { children: ReactNode; style?: object }) { const { colors } = useResumarkTheme(); return <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }, style]}>{children}</View>; }
const styles = StyleSheet.create({ label: { fontSize: 10, fontWeight: '900', letterSpacing: 1.35 }, primary: { minHeight: 54, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10, borderRadius: 8, paddingHorizontal: 18 }, primaryText: { fontSize: 15, fontWeight: '800' }, arrow: { fontSize: 21, fontWeight: '500' }, outline: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderRadius: 7, paddingHorizontal: 14 }, outlineText: { fontSize: 14, fontWeight: '700' }, card: { borderWidth: 1, borderRadius: 12, padding: 18 }, pressed: { opacity: .8 }, disabled: { opacity: .45 } });
